# These are supported funding model platforms

github: JosephWoodall
patreon: # Replace with your patreon username
open_collective: # Replace with your open collective username
ko_fi: # Replace with your ko-fi username
custom: # Replace with a custom funding URL
