"""
conversation.py — Uchi's chit-chat engine.

Social turns are free-generated by a small dialogue-trained decoder and are NOT
passed through the fact-check oracle: they assert no facts, so there is nothing to
hallucinate. This is what gives Uchi a personality without weakening the
zero-confabulation guarantee on factual answers (which still go through
Generate-and-Ground).

A short rolling window of recent turns is prepended so replies stay contextual
("my dog is sick" → "I'm sorry" → "he'll be okay" needs to know who "he" is).
"""
from __future__ import annotations


class ConversationEngine:
    """Wrap a dialogue decoder + a working-memory turn window."""

    def __init__(self, decoder, window: int = 4) -> None:
        self.decoder = decoder          # uchi.decoder.NeuralDecoder (chat checkpoint)
        self.window = window
        self.history: list[tuple[str, str]] = []   # [(user, bot), ...]

    def reply(self, message: str) -> str:
        parts: list[str] = []
        for user, bot in self.history[-self.window:]:
            parts.append(user)
            parts.append(bot)
        parts.append(message)
        context = " ".join(parts)
        try:
            resp = (self.decoder.generate(context, []) or "").strip()
        except Exception:
            resp = ""
        if not resp:
            resp = "I'm here — tell me more."
        self.history.append((message, resp))
        return resp

    def reset(self) -> None:
        self.history = []
