"""react_warmup_train.py — ReAct-format warmup fine-tune, ahead of Item 6.

Item 6's real GPU calibration (25 real SWE-Gym instances, 100 branches)
got zero reward on every branch. Direct inspection of the raw model output
at real ReAct-episode prompt length showed why: the model has never been
shown the `Thought:/Action:/Observation:` tagged format `agentic_repair.py`'s
system prompt asks for, in ANY training phase (SFT: SQuAD/Dolly/CodeAlpaca/
UltraChat, plain Q&A; CoT: GSM8K/OpenOrca/Magicoder/CommitPackFT --
CommitPackFT teaches diff *reading*, never a tool-use trajectory). Asking a
64M-param model to invent a structured protocol zero-shot, with zero
fine-tuning exposure to it, produced complete structureless gibberish, not
a near-miss on formatting.

This is standard behavior-cloning-before-RL practice (AlphaGo's supervised
policy network before self-play RL, Silver et al. 2016; SFT-before-RLHF,
Ouyang et al. 2022) -- Item 6's own module docstring already named this
exact failure mode (uniform zero reward -> degenerate GRPO advantage) as
the reason it doesn't try to route around needing a competent proposer.

**Fully real, no-LLM data** -- .uchi/corpus/swe_gym_full.jsonl's 2,438
curated instances already have real, human-authored, gold-standard patches
for real, resolved GitHub issues. Every Action/Observation in each
constructed trace is a real tool call (real file read, real patch applied,
real tests run) against a real repo checkout -- only the connective English
narration ("Thought: ...") is templated scaffolding, same standard
`cot_distill.py`'s existing "real teacher trace" sources already claim.

**v2 (this version) fixes a real training/inference mismatch found after
v1's result**: `agentic_repair.run_react_episode` calls `generate_fn` ONCE
PER TURN at real inference, expecting one short Thought+Action (or
Thought+Final-Answer) completion, with the real tool's Observation appended
by the harness afterward -- never generated by the model. v1 trained on one
long completion containing the WHOLE multi-turn trace, loss applied to
everything including the (templated) Observation text, teaching the model
to keep generating past an action and to predict/hallucinate tool output --
exactly backwards from the real task. This is why v1's real Item 6
calibration re-check (25 instances, 100 branches) got zero reward, same as
before the warmup, despite training loss looking fine. Fixed by decomposing
each real trace into per-turn (prompt, target) pairs mirroring
`run_react_episode`'s own prompt/memory construction exactly -- loss masked
to each turn's own short target only, real Observations are context, never
a generation target. Standard multi-turn tool-use SFT practice (Toolformer,
Gorilla, FireAct/AgentTune-style fine-tuning all mask loss to the agent's
own turns) -- not a new invention, just correctly applied here for the
first time.

Continues from the current (QAT'd) flux_best.pt, quantization kept ON
throughout (the checkpoint's weights were only ever optimized for the
ternary-quantized forward pass -- training in full precision now would be
just as wrong as evaluating it in full precision later). Mixed with
CoT-recovery macro-steps (reusing cot_distill.py's load_cot_examples/
make_batches directly) for the same anti-forgetting reason qat_train.py's
own CoT/text mix exists.

Usage:
    .venv/bin/python -m uchi.flux.react_warmup_train --base uchi/flux/checkpoints/flux_best.pt \\
        --pruned-vocab uchi/flux/checkpoints/pruned_vocab_0_5_0_32k.json --max-examples 300
"""
from __future__ import annotations

import math
import os
import random
import re
import time
import argparse

import torch
import torch.nn as nn

from uchi.agentic_repair import _OBSERVATION_CHAR_CAP

from .cot_distill import load_cot_examples, make_batches
from .train_v2 import save_checkpoint

DEFAULTS = dict(
    micro_batch_size=1,
    grad_accum_steps=8,       # effective batch = 8 -- NOT 64. Real-measured: at seq_len=2048,
                              # micro_batch=1, gradient checkpointing, one micro-step costs ~5.3s
                              # on this GPU (measured via a live smoke run at grad_accum=2). 64
                              # would make each macro-step ~5.6min (a 300-step run ~28h) -- this
                              # is a small, precious ~300-example curated dataset, not a giant
                              # corpus, so it doesn't need SFT/QAT's eff_batch=64 convention;
                              # eff_batch=8 keeps per-macro-step cost to ~42s (measured, see below)
    max_seq_len=2048,          # v2 per-turn examples, real-measured (untruncated -- v1's
                               # measurement was corrupted by encode_text's own silent
                               # max_length=1024 default, a real bug fixed alongside this):
                               # min=393, median=1446, p90=2719, max=3095 tokens across 40 real
                               # per-turn examples. 3072 (covers ~everything) real-OOM'd on this
                               # 12GB GPU even with gradient checkpointing at micro_batch=1;
                               # 2048 is the largest value already proven to fit (v1 ran clean
                               # at this size) -- keeps 82% of real examples, drops the rest
                               # (same "drop if too long" practice every phase script already uses)
    max_steps=300,
    warmup_steps=30,
    learning_rate=5e-6,        # gentlest LR yet -- 5th sequential fine-tune, on a quantized model
    min_lr_frac=0.1,
    weight_decay=0.01,
    grad_clip=1.0,
    checkpoint_interval=100,
    eval_interval=50,
    log_interval=10,
    checkpoint_dir="uchi/flux/checkpoints",
    max_examples=300,
    cot_examples=1000,
    cot_frac=0.3,              # recovery fraction; 0.7 of steps train the new ReAct skill
)


def _build_react_turns(record: dict, tools, primary_file: str) -> list[dict]:
    """The real per-turn ReAct trace for one curated SWE-Gym instance,
    decomposed into discrete turns -- NOT one flat trace. Each turn is
    `{"target": str, "memory_entries": [str, ...]}`:

    - `target` is that turn's own `Thought:` + `Action:` (full form, e.g.
      the complete `<<<PATCH>>>...<<<END_PATCH>>>` block) or, for the last
      turn, `Thought:` + `Final Answer:` -- this is what the model must
      learn to *generate*.
    - `memory_entries` are the lines `run_react_episode` itself would have
      appended to `memory` after this turn actually ran, INCLUDING the real
      Observation -- these become later turns' *input context*, never a
      generation target for any turn. Critically, a turn's own `target` and
      its own `memory_entries` differ for apply_patch: the target contains
      the full diff (what the model must produce), the memory entry is the
      abbreviated `apply_patch[<N-char diff>]` form -- matching
      `run_react_episode`'s own memory-append behavior exactly, since real
      inference-time context never contains the full diff again after the
      turn that produced it.

    Every Action/Observation is a real tool call against a real repo with
    the real gold patch; only the Thought/Final Answer English is templated
    scaffolding.
    """
    turns = []

    thought1 = f"Thought: Let me look at {primary_file} to understand the issue."
    action1 = f"Action: read_file[{primary_file}]"
    read_result = tools.execute("read_file", primary_file)
    obs1 = f"Observation: {read_result.output[:_OBSERVATION_CHAR_CAP]}"
    turns.append({"target": f"{thought1}\n{action1}", "memory_entries": [thought1, action1, obs1]})

    thought2 = "Thought: I'll apply a fix for this issue."
    action2_full = f"Action: apply_patch\n<<<PATCH>>>\n{record['patch']}\n<<<END_PATCH>>>"
    action2_abbrev = f"Action: apply_patch[<{len(record['patch'])}-char diff>]"
    apply_result = tools.execute("apply_patch", record["patch"])
    obs2 = f"Observation: {apply_result.output[:_OBSERVATION_CHAR_CAP]}"
    turns.append({"target": f"{thought2}\n{action2_full}", "memory_entries": [thought2, action2_abbrev, obs2]})

    test_ids = list(record["fail_to_pass"]) + list(record["pass_to_pass"])
    thought3 = "Thought: Let me verify the fix."
    action3 = f"Action: run_tests[{','.join(test_ids)[:200]}]"
    test_result = tools.execute("run_tests", ",".join(test_ids))
    obs3 = f"Observation: {test_result.output[:_OBSERVATION_CHAR_CAP]}"
    turns.append({"target": f"{thought3}\n{action3}", "memory_entries": [thought3, action3, obs3]})

    thought4 = "Thought: The tests pass, the issue is resolved."
    final4 = f"Final Answer: Fixed by updating {primary_file}."
    turns.append({"target": f"{thought4}\n{final4}", "memory_entries": [thought4, final4]})

    return turns


def build_react_example(record: dict, sandbox) -> list[dict] | None:
    """Constructs the real per-turn (prompt, target) pairs for one curated
    SWE-Gym record, or None if the instance can't be cloned/has no
    identifiable touched file. Uses `sandbox.checkout_repo` (isolated copy,
    source clone never mutated) -- same pattern `GRPOTrainer._sample_branch`
    already uses, not the raw `ensure_local_clone` cache directly.

    Each turn's `prompt` mirrors `run_react_episode`'s own prompt
    construction exactly (`system_prompt + Issue + prior memory joined`) --
    turn *i*'s prompt includes the real accumulated history from turns
    `1..i-1`, so the model trains on exactly the input shape it sees at real
    inference, not a bare prompt every time.
    """
    from uchi.agentic_repair import _build_system_prompt
    from uchi.code_retrieval import extract_patch_files
    from uchi.repo_fetch import RepoFetchError, ensure_local_clone
    from uchi.tools import RepoToolRegistry

    try:
        repo_path = ensure_local_clone(record["repo"], record["base_commit"])
    except RepoFetchError:
        return None

    files = sorted(extract_patch_files(record["patch"]))
    if not files:
        return None
    primary_file = files[0]

    try:
        repo_dir = sandbox.checkout_repo(repo_path, base_commit=record.get("base_commit"))
        tools = RepoToolRegistry(sandbox, repo_dir)
        turns = _build_react_turns(record, tools, primary_file)
        system_prompt = _build_system_prompt(tools)
    except (OSError, RuntimeError) as e:
        # Real repos at 300-instance scale hit real, exotic edge cases
        # (a broken-symlink copytree crash already found and fixed at the
        # sandbox level this session; there will be others -- a bad
        # checkout shouldn't take down the whole construction batch over
        # one repo). Skip, don't crash.
        print(f"    [!] skipping {record.get('instance_id', '?')}: {e}")
        return None

    base_prompt = f"{system_prompt}\n\nIssue:\n{record['problem_statement']}\n\n"
    examples = []
    memory: list[str] = []
    for turn in turns:
        prompt_text = base_prompt + ("\n".join(memory) + "\n" if memory else "")
        examples.append({"prompt": prompt_text, "target": turn["target"]})
        memory.extend(turn["memory_entries"])
    return examples


def load_react_examples(tokenizer, max_seq_len: int, max_examples: int,
                         curriculum_path: str, sandbox_timeout: float = 120.0, seed: int = 42) -> list[dict]:
    """Constructs real, PER-TURN ReAct teacher examples from
    `swe_gym_full.jsonl`'s curated, gold-patched instances (same curriculum
    Item 6 uses, easy -> hard order via `load_curriculum`). `max_examples`
    counts real curriculum *instances* processed, not the (larger) number of
    per-turn training examples that come out -- each instance's trace
    decomposes into several turns (`build_react_example`), so the returned
    list is longer than `max_examples`.

    Tokenized to `<|user|>{prompt so far}<|think|>{this turn's target}<|eos|>`
    -- matching exactly how `build_generate_fn_from_model`'s
    `generate_fn(think=True)` is called once per turn at real inference
    (`agentic_repair.run_react_episode`): `decode_text` already drops
    special-token boundaries, so no separate `<|/think|><|assistant|>` turn
    is needed for this path. The critical fix over the first attempt: loss
    is masked to each turn's own short target only -- prior turns' real
    Observations live in the prompt (context), never in any loss target, so
    the model is never trained to predict/hallucinate a tool's output."""
    from uchi.execution_sandbox import ExecutionSandbox
    from uchi.grpo import load_curriculum

    random.seed(seed)
    sandbox = ExecutionSandbox(timeout=sandbox_timeout)
    buckets = load_curriculum(curriculum_path)

    print("  Constructing real ReAct teacher traces from real, gold-standard SWE-Gym patches ...")
    raw_examples = []
    n_instances = 0
    for bucket in buckets:
        for record in bucket:
            if n_instances >= max_examples:
                break
            turn_examples = build_react_example(record, sandbox)
            if turn_examples is not None:
                raw_examples.extend(turn_examples)
                n_instances += 1
        if n_instances >= max_examples:
            break
    print(f"  Constructed {len(raw_examples)} real per-turn examples from {n_instances} real instances")

    user_id = tokenizer.encode_special("<|user|>")
    think_id = tokenizer.encode_special("<|think|>")
    eos_id = tokenizer.eos_token_id
    pad_id = tokenizer.pad_token_id

    formatted = []
    n_dropped_too_long = 0
    for ex in raw_examples:
        # encode_text's OWN default max_length is 1024 -- silently
        # truncating (keeping the FRONT, dropping the tail) if not
        # overridden. Passing max_seq_len explicitly here means truncation
        # decisions are made once, deliberately, by the drop check below --
        # not silently inside the tokenizer for anything that would
        # otherwise fit.
        prompt_ids = [user_id] + tokenizer.encode_text(ex["prompt"], max_length=max_seq_len)
        target_ids = [think_id] + tokenizer.encode_text(ex["target"], max_length=max_seq_len) + [eos_id]
        full_ids = prompt_ids + target_ids

        if len(full_ids) > max_seq_len:
            n_dropped_too_long += 1
            continue

        n_prompt = len(prompt_ids)
        loss_mask = [0] * min(n_prompt, len(full_ids)) + [1] * max(0, len(full_ids) - n_prompt)
        n_pad = max_seq_len - len(full_ids)
        full_ids = full_ids + [pad_id] * n_pad
        loss_mask = loss_mask + [0] * n_pad
        formatted.append({"input_ids": full_ids[:max_seq_len], "loss_mask": loss_mask[:max_seq_len]})

    print(f"  Tokenized {len(formatted)} examples ({n_dropped_too_long} dropped -- too long for seq_len={max_seq_len})")
    return formatted


def masked_ce_loss(logits, targets, mask):
    logits_flat = logits.reshape(-1, logits.size(-1))
    targets_flat = targets.reshape(-1)
    mask_flat = mask.reshape(-1)
    loss_per_token = nn.functional.cross_entropy(logits_flat, targets_flat, reduction="none")
    return (loss_per_token * mask_flat).sum() / mask_flat.sum().clamp(min=1)


def main():
    parser = argparse.ArgumentParser(description="FLUX ReAct-format warmup fine-tune (ahead of 0.5.0 Item 6)")
    parser.add_argument("--base", type=str, required=True, help="Path to the (QAT'd) FLUX checkpoint")
    parser.add_argument("--pruned-vocab", type=str, default=None,
                        help="Path to the PrunedVocab JSON --base was trained with.")
    parser.add_argument("--curriculum", type=str, default=".uchi/corpus/swe_gym_full.jsonl")
    parser.add_argument("--max-examples", type=int, default=DEFAULTS["max_examples"],
                        help="Real instances to construct ReAct traces from -- no silent full-"
                             "corpus default, calibrate first.")
    parser.add_argument("--steps", type=int, default=DEFAULTS["max_steps"])
    parser.add_argument("--lr", type=float, default=DEFAULTS["learning_rate"])
    parser.add_argument("--micro-batch", type=int, default=DEFAULTS["micro_batch_size"])
    parser.add_argument("--grad-accum", type=int, default=DEFAULTS["grad_accum_steps"])
    parser.add_argument("--seq-len", type=int, default=DEFAULTS["max_seq_len"])
    parser.add_argument("--cot-frac", type=float, default=DEFAULTS["cot_frac"],
                        help="Probability a macro-step trains on CoT-recovery data vs the new ReAct skill")
    parser.add_argument("--cot-examples", type=int, default=DEFAULTS["cot_examples"])
    parser.add_argument("--no-compile", action="store_true", default=True,
                        help="Kept True by default -- this GPU's torch.compile autotune stall "
                             "history this session (cot_distill.py) makes eager mode the safe default.")
    parser.add_argument("--checkpoint-dir", type=str, default=DEFAULTS["checkpoint_dir"])
    args = parser.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"

    from .tokenizer_v2 import TikTokenHybridTokenizer
    from .model import HybridTSSM

    if args.pruned_vocab:
        from .vocab_prune import load_pruned_tokenizer
        tokenizer = load_pruned_tokenizer(args.pruned_vocab)
        print(f"  Tokenizer:    pruned, vocab_size={tokenizer.vocab_size:,} (from {args.pruned_vocab})")
    else:
        tokenizer = TikTokenHybridTokenizer()
        print(f"  Tokenizer:    full cl100k_base, vocab_size={tokenizer.vocab_size:,}")

    print("=" * 72)
    print("FLUX — ReAct-format warmup fine-tune (ahead of 0.5.0 Item 6)")
    print("=" * 72)

    ckpt = torch.load(args.base, map_location=device, weights_only=False)
    sd = ckpt["model"] if isinstance(ckpt, dict) and "model" in ckpt else ckpt
    emb_shape = sd["embedding.weight"].shape
    vocab_size, d_model = int(emb_shape[0]), int(emb_shape[1])
    layer_ids = {int(m.group(1)) for k in sd if (m := re.match(r"layers\.(\d+)\.", k))}
    n_layers = (max(layer_ids) + 1) if layer_ids else 12

    model = None
    for d_state in (64, 32, 16, 128):
        try:
            m = HybridTSSM(
                vocab_size=vocab_size, syntax_vocab_size=tokenizer.syntax_vocab_size,
                d_model=d_model, n_layers=n_layers, d_state=d_state,
            ).to(device)
            m.load_state_dict(sd, strict=False)
            model = m
            break
        except Exception:
            continue
    if model is None:
        raise RuntimeError("Could not match architecture to checkpoint")

    # The checkpoint's weights were only ever optimized for the ternary-
    # quantized forward pass -- keep it on for the whole run, same
    # rationale qat_train.py documents for its own CoT-format steps.
    was_quantized = bool(ckpt.get("quantized", False)) if isinstance(ckpt, dict) else False
    if was_quantized:
        print("  [!] Base checkpoint is QAT'd -- keeping 1.58-bit ternary quantization ON")
        model.set_quantization(True)
    model._gradient_checkpointing = True
    model.train()

    n_params = sum(p.numel() for p in model.parameters())
    print(f"  Base:         {args.base}")
    print(f"  Parameters:   {n_params:,} ({n_params / 1e6:.1f}M)")

    react_data = load_react_examples(tokenizer, args.seq_len, args.max_examples, args.curriculum)
    if not react_data:
        raise RuntimeError(
            "No ReAct examples were constructed (all instances failed to clone or had no "
            "identifiable touched file) -- nothing to train on."
        )
    n_val = max(1, int(len(react_data) * 0.1))
    react_val, react_train = react_data[:n_val], react_data[n_val:]
    print(f"  ReAct train:  {len(react_train):,}  ReAct val: {len(react_val):,}")

    print("  Loading CoT reasoning traces (recovery, real GSM8K teacher traces) ...")
    cot_data = load_cot_examples(tokenizer, args.seq_len, args.cot_examples)
    n_cot_val = max(10, int(len(cot_data) * 0.1))
    cot_val, cot_train = cot_data[:n_cot_val], cot_data[n_cot_val:]
    print(f"  CoT train:    {len(cot_train):,}  CoT val:   {len(cot_val):,}")

    def _cycle(data):
        while True:
            for batch in make_batches(data, args.micro_batch, shuffle=True):
                yield batch

    react_train_iter = _cycle(react_train)
    cot_train_iter = _cycle(cot_train)

    max_steps = args.steps
    warmup_steps = min(DEFAULTS["warmup_steps"], max(1, max_steps // 10))
    lr_min = args.lr * DEFAULTS["min_lr_frac"]

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=args.lr,
        weight_decay=DEFAULTS["weight_decay"], betas=(0.9, 0.95),
    )

    def get_lr(step):
        if step < warmup_steps:
            return args.lr * (step + 1) / max(1, warmup_steps)
        if step >= max_steps:
            return lr_min
        progress = (step - warmup_steps) / max(1, (max_steps - warmup_steps))
        coeff = 0.5 * (1.0 + math.cos(math.pi * progress))
        return lr_min + coeff * (args.lr - lr_min)

    @torch.no_grad()
    def evaluate(data):
        model.eval()
        total_loss, n = 0.0, 0
        for X, Y, mask in make_batches(data, args.micro_batch, shuffle=False):
            X, Y, mask = X.to(device), Y.to(device), mask.to(device)
            logits, _ = model(X)
            loss = masked_ce_loss(logits, Y, mask)
            total_loss += loss.item()
            n += 1
        model.train()
        avg = total_loss / max(n, 1)
        return avg, math.exp(min(avg, 20.0))

    ckpt_dir = args.checkpoint_dir
    os.makedirs(ckpt_dir, exist_ok=True)
    best_react_val = float("inf")
    rng = random.Random(123)
    t0 = time.time()

    print(f"\n  Starting ReAct warmup: {max_steps} macro-steps "
          f"(cot_frac={args.cot_frac}, eff_batch={args.micro_batch * args.grad_accum}, seq_len={args.seq_len})\n")

    for step in range(max_steps):
        lr = get_lr(step)
        for pg in optimizer.param_groups:
            pg["lr"] = lr

        is_cot_step = rng.random() < args.cot_frac
        data_iter = cot_train_iter if is_cot_step else react_train_iter
        optimizer.zero_grad(set_to_none=True)
        loss_accum = 0.0

        for _ in range(args.grad_accum):
            X, Y, mask = next(data_iter)
            X, Y, mask = X.to(device), Y.to(device), mask.to(device)
            logits, _ = model(X)
            loss = masked_ce_loss(logits, Y, mask)
            (loss / args.grad_accum).backward()
            loss_accum += loss.item() / args.grad_accum

        torch.nn.utils.clip_grad_norm_(model.parameters(), DEFAULTS["grad_clip"])
        optimizer.step()

        if (step + 1) % DEFAULTS["log_interval"] == 0:
            elapsed = time.time() - t0
            ms_per_step = (elapsed * 1000) / DEFAULTS["log_interval"]
            t0 = time.time()
            kind = "cot  " if is_cot_step else "react"
            print(f"  Step {step + 1:05d}/{max_steps} │ [{kind}] Loss: {loss_accum:.4f} │ LR: {lr:.2e} │ {ms_per_step:.0f}ms/step")

        if (step + 1) % DEFAULTS["eval_interval"] == 0:
            react_loss, react_ppl = evaluate(react_val)
            is_best = react_loss < best_react_val
            if is_best:
                best_react_val = react_loss
            print(f"\n  ──── VAL step {step + 1:05d} │ ReAct loss {react_loss:.4f} (PPL {react_ppl:.1f}) "
                  f"{'★ best' if is_best else ''}\n")
            if is_best:
                save_checkpoint(model, optimizer, step + 1, best_react_val,
                                 os.path.join(ckpt_dir, "react_warmup_best.pt"), quantized=was_quantized)

        if (step + 1) % DEFAULTS["checkpoint_interval"] == 0:
            save_checkpoint(model, optimizer, step + 1, best_react_val,
                             os.path.join(ckpt_dir, f"react_warmup_{step + 1:05d}.pt"), quantized=was_quantized)

    final_path = os.path.join(ckpt_dir, "react_warmup_final.pt")
    save_checkpoint(model, optimizer, max_steps, best_react_val, final_path, quantized=was_quantized)
    print(f"\n  ReAct warmup complete. Best ReAct val loss: {best_react_val:.4f}")
    print(f"  Final checkpoint: {final_path}")


if __name__ == "__main__":
    main()
